### ISSUE TITLE
Optional payload/meta properties

### ISSUE THREAD

**Issue by rplotkin** [redux-utilities/flux-standard-action#100] opened 2018-01-17 14:31 UTC
payload: Payload
and
meta: Meta
are not defined as optional properties (with "?")
yet they are supposed to be optional. I have not been able to get this to work without explicitly null values; is there a way to have an action with _only_ a type, or are these fields _not_ optional?

**Comment by JaKXz** [comment] 2018-01-17 15:41
Thank you for the issue! I just merged #94 and perhaps we need something similar for `payload`.

**Comment by dsanders1234** [comment] 2018-04-30 18:40
It seems like the typescript def should be:

/**
 * [FluxStandardAction](https://github.com/redux-utilities/flux-standard-action)
 *
 * Redux Actions should generally either extend this interface or [[ActionWithEventAnalytics]],
 * depending on whether or not the action is to be associated with google analytics event tracking.
 */
export interface FluxStandardAction<P=undefined, M=undefined> extends Action {
   /**
    * The `type` of an action identifies to the consumer the nature of the action that has occurred.
    * Two actions with the same `type` MUST be strictly equivalent (using `===`)
    */
   type: string;
   /**
    * The optional `payload` property MAY be any type of value.
    * It represents the payload of the action.
    * Any information about the action that is not the type or status of the action should be part of the `payload` field.
    * By convention, if `error` is `true`, the `payload` SHOULD be an error object.
    * This is akin to rejecting a promise with an error object.
    */
   payload?: P | undefined;
   /**
    * The optional `error` property MAY be set to true if the action represents an error.
    * An action whose `error` is true is analogous to a rejected Promise.
    * By convention, the `payload` SHOULD be an error object.
    * If `error` has any other value besides `true`, including `undefined`, the action MUST NOT be interpreted as an error.
    */
   error?: boolean;
   /**
    * The optional `meta` property MAY be any type of value.
    * It is intended for any extra information that is not part of the payload.
    */
   meta?: M | undefined;
}

**Comment by dsanders1234** [comment] 2018-05-01 15:07
The problem is that this "standard action" format does not lend itself to typescript very well.  In reality, one should have an interface for each type of action:

ActionWithPayload<P> extends Action
ActionWithMeta<M> extends Action
ActionWithPayloadAndMeta<P,M> extends ActionWithPayload<P>

etc.

**Comment by sstarrAtmeta** [comment] 2018-05-15 18:20
I believe this issue should now be closed, since the following commit will have made `payload` optional.
https://github.com/redux-utilities/flux-standard-action/commit/62deb4ac6c83094c2cb3c41495febce3ac62a7d5

**Comment by JaKXz** [comment] 2018-07-26 01:49
I'm going to close this as fixed in the latest published version, but please feel free to re-open if you are still experiencing issues!

**Closed by JaKXz** 2018-07-26 01:49 UTC
